"""
NetworkCanvasProtocol — 2D 네트워크 캔버스 교체 가능 인터페이스

main.py가 구체 구현체(IsometricView)에 직접 결합되지 않도록,
실사용 표면 API만 Protocol로 정의한다.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class NetworkCanvasProtocol(Protocol):
    """메인 윈도우가 의존하는 캔버스 인터페이스."""

    # --- selection state ---
    selected_node_name: str | None
    selected_pipe_key: tuple[str, str] | None
    @property
    def multi_selected_pipes(self) -> frozenset[tuple[str, str]]: ...
    @property
    def multi_selected_nodes(self) -> frozenset[str]: ...

    # --- signal-like (PySide6 Signal in concrete impl) ---
    selection_changed: Any

    # --- public sub-objects ---
    scene: Any
    minimap: Any

    # --- drawing / theme ---
    def draw_all(self) -> None: ...
    def force_full_rebuild(self) -> None: ...
    def set_dark_mode(self, enabled: bool) -> None: ...
    def update_single_pipe_visual(self, pipe_key: tuple[str, str]) -> bool: ...
    def update_single_node_visual(self, node_name: str) -> bool: ...

    # --- selection ---
    def update_selection(
        self,
        node_name: str | None = None,
        pipe_key: tuple[str, str] | None = None,
    ) -> None: ...
    def clear_multi_selection(self) -> None: ...
    def clear_multi_node_selection(self) -> None: ...
    def replace_multi_pipe_selection(self, pipe_keys: list[tuple[str, str]]) -> None: ...
    def replace_multi_node_selection(self, node_names: list[str]) -> None: ...

    # --- coordinate / navigation ---
    def to_screen_coord(self, x: float, y: float, z: float) -> tuple[float, float]: ...
    def centerOn(self, x: float, y: float) -> None: ...
    def center_on_node(self, node_name: str) -> None: ...
    def zoom_fit(self) -> None: ...
    def has_view_bookmark(self) -> bool: ...
    def zoom_restore_previous(self) -> bool: ...

    # --- label panel ---
    def toggle_label_panel(self) -> None: ...
    def is_label_panel_visible(self) -> bool: ...

    # --- interaction mode ---
    def stop_and_exit_interaction_mode(self) -> None: ...

    # --- focus ---
    def setFocus(self) -> None: ...


__all__ = ["NetworkCanvasProtocol"]
